trigger:
  - master # Branch to trigger the build

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  azureServiceConnection: 'connectionYouCreated'
  azureAppServiceName: 'yourAppService'
  deployToSlot: 'yourSlotName'
  projectToDeploy: 'yourWebAppOrApiProject.csproj'
  packageName: 'Api.zip' # Use the FOLDER name of the projectToDeploy.

steps:
- task: DotNetCoreCLI@2
  displayName: Build All $(buildConfiguration)
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Zip $(projectToDeploy) to $(packageName)
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/$(projectToDeploy)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  displayName: Deploy to $(deployToSlot) slot
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(azureAppServiceName)'
    slotName: '$(deployToSlot)'
    package: $(System.ArtifactsDirectory)/**/$(packageName)
    deploymentMethod: auto
